"""add date and time to invitation table

Revision ID: 1c008b8b553a
Revises: 2fff4670a1b1
Create Date: 2024-10-01 00:17:56.315549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c008b8b553a'
down_revision: Union[str, None] = '2fff4670a1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('date', sa.String(), nullable=True))
    op.add_column('invitations', sa.Column('time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'time')
    op.drop_column('invitations', 'date')
    # ### end Alembic commands ###
