"""add room_id to invitation table

Revision ID: 2fff4670a1b1
Revises: b12d5a0a5070
Create Date: 2024-09-30 23:55:59.515341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fff4670a1b1'
down_revision: Union[str, None] = 'b12d5a0a5070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('room_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_invitations_room_id'), 'invitations', ['room_id'], unique=False)
    op.drop_index('ix_users_new_id', table_name='users')
    op.drop_index('ix_users_new_student_id', table_name='users')
    op.drop_index('ix_users_new_username', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_student_id'), 'users', ['student_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_student_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('ix_users_new_username', 'users', ['username'], unique=1)
    op.create_index('ix_users_new_student_id', 'users', ['student_id'], unique=1)
    op.create_index('ix_users_new_id', 'users', ['id'], unique=False)
    op.drop_index(op.f('ix_invitations_room_id'), table_name='invitations')
    op.drop_column('invitations', 'room_id')
    # ### end Alembic commands ###
