"""baseline migration

Revision ID: 47f71bcd886a
Revises: 
Create Date: 2024-09-27 13:56:00.853765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f71bcd886a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_reservation', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('room_reservation', sa.Column('room_id', sa.Integer(), nullable=True))
    op.add_column('room_reservation', sa.Column('date', sa.String(), nullable=True))
    op.add_column('room_reservation', sa.Column('time', sa.String(), nullable=True))
    op.create_index(op.f('ix_room_reservation_id'), 'room_reservation', ['id'], unique=False)
    op.create_index(op.f('ix_room_reservation_room_id'), 'room_reservation', ['room_id'], unique=False)
    op.create_foreign_key(None, 'room_reservation', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_reservation', type_='foreignkey')
    op.drop_index(op.f('ix_room_reservation_room_id'), table_name='room_reservation')
    op.drop_index(op.f('ix_room_reservation_id'), table_name='room_reservation')
    op.drop_column('room_reservation', 'time')
    op.drop_column('room_reservation', 'date')
    op.drop_column('room_reservation', 'room_id')
    op.drop_column('room_reservation', 'user_id')
    # ### end Alembic commands ###
