"""Add students in Reservation model

Revision ID: c6d56d44a7c0
Revises: 0ac6e243a505
Create Date: 2024-09-29 23:23:52.785812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d56d44a7c0'
down_revision: Union[str, None] = '0ac6e243a505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_reservation', sa.Column('students', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_reservation', 'students')
    # ### end Alembic commands ###
