"""add topics column in problem model

Revision ID: 235a711deafe
Revises: 
Create Date: 2024-10-03 22:46:02.354992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '235a711deafe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('topics', sa.String(), nullable=True))
    op.create_index(op.f('ix_problems_topics'), 'problems', ['topics'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problems_topics'), table_name='problems')
    op.drop_column('problems', 'topics')
    # ### end Alembic commands ###
