"""change name from topic to level column in problem model

Revision ID: 40056d7a9b9b
Revises: f9632451ec72
Create Date: 2024-10-03 23:11:24.777261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40056d7a9b9b'
down_revision: Union[str, None] = 'f9632451ec72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('level', sa.String(), nullable=True))
    op.drop_index('ix_problems_topic', table_name='problems')
    op.create_index(op.f('ix_problems_level'), 'problems', ['level'], unique=False)
    op.drop_column('problems', 'topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('topic', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_problems_level'), table_name='problems')
    op.create_index('ix_problems_topic', 'problems', ['topic'], unique=False)
    op.drop_column('problems', 'level')
    # ### end Alembic commands ###
