"""change name from topics to topic column in problem model

Revision ID: f9632451ec72
Revises: 235a711deafe
Create Date: 2024-10-03 23:05:56.980871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9632451ec72'
down_revision: Union[str, None] = '235a711deafe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('topic', sa.String(), nullable=True))
    op.drop_index('ix_problems_topics', table_name='problems')
    op.create_index(op.f('ix_problems_topic'), 'problems', ['topic'], unique=False)
    op.drop_column('problems', 'topics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('topics', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_problems_topic'), table_name='problems')
    op.create_index('ix_problems_topics', 'problems', ['topics'], unique=False)
    op.drop_column('problems', 'topic')
    # ### end Alembic commands ###
